server:
  port: 8085

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:postgresql://localhost:5432/plazoletadb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

jwt:
  secret-key: UltraClaveSuperSecretaIndescifrable32

mensajeria:
  url: http://localhost:8087